#!/bin/bash

# Quick Manual Deployment Guide
# Run these commands one by one to deploy

echo "=== QUICK DEPLOYMENT GUIDE ==="
echo ""
echo "1. Build and push to ECR:"
echo "   ./deploy-simple.sh"
echo ""
echo "2. Create/update task definition:"
echo "   aws ecs register-task-definition --cli-input-json file://ecs-task-definition.json --region us-east-1"
echo ""
echo "3. Create ECS cluster (if needed):"
echo "   aws ecs create-cluster --cluster-name glossary-cluster --region us-east-1"
echo ""
echo "4. Create ECS service (replace SUBNET_IDS and SECURITY_GROUP_ID):"
echo "   aws ecs create-service --region us-east-1 \\"
echo "     --cluster glossary-cluster \\"
echo "     --service-name glossary-service \\"
echo "     --task-definition glossary-task:1 \\"
echo "     --desired-count 1 \\"
echo "     --launch-type FARGATE \\"
echo "     --network-configuration 'awsvpcConfiguration={subnets=[subnet-xxx,subnet-yyy],securityGroups=[sg-xxx],assignPublicIp=ENABLED}'"
echo ""
echo "5. Get service IP:"
echo "   aws ecs describe-tasks --cluster glossary-cluster --tasks \$(aws ecs list-tasks --cluster glossary-cluster --service-name glossary-service --query 'taskArns[0]' --output text --region us-east-1) --query 'tasks[0].attachments[0].details[?name==\`networkInterfaceId\`].value' --output text --region us-east-1 | xargs -I {} aws ec2 describe-network-interfaces --network-interface-ids {} --query 'NetworkInterfaces[0].Association.PublicIp' --output text --region us-east-1"
echo ""
echo "=== OR USE AWS CONSOLE ==="
echo "1. Go to ECS Console"
echo "2. Create/Select cluster: glossary-cluster"  
echo "3. Create service using task definition: glossary-task"
echo "4. Use Fargate launch type"
echo "5. Enable public IP"
echo ""
